[phases.setup]
nixPkgs = ["python311", "gcc", "libpq", "tesseract", "poppler_utils", "liberation_ttf"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "sh -c 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'"
